# Generated by Django 5.1.5 on 2025-02-10 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra Large')], max_length=2)),
                ('crust', models.CharField(choices=[('thin', 'Thin'), ('thick', 'Thick'), ('normal', 'Normal'), ('gluten_free', 'Gluten Free')], max_length=15)),
                ('sauce', models.CharField(choices=[('tomato', 'Tomato'), ('bbq', 'BBQ'), ('harissa', 'Harissa')], max_length=15)),
                ('cheese', models.CharField(choices=[('mozarella', 'Mozarella'), ('vegan', 'Vegan'), ('low_fat', 'Low Fat'), ('parmesan', 'Parmesan')], max_length=15)),
                ('toppings', models.CharField(choices=[('pepperoni', 'Pepperoni'), ('chicken', 'Chicken'), ('ham', 'Ham'), ('pineapple', 'Pineapple'), ('peppers', 'Peppers'), ('mushrooms', 'Mushrooms'), ('onions', 'Onions')], max_length=15)),
                ('pepperoni', models.BooleanField(default=False)),
                ('chicken', models.BooleanField(default=False)),
                ('ham', models.BooleanField(default=False)),
                ('pineapple', models.BooleanField(default=False)),
                ('peppers', models.BooleanField(default=False)),
                ('mushrooms', models.BooleanField(default=False)),
                ('onions', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('card_number', models.CharField(max_length=16)),
                ('card_expiration_date', models.CharField(max_length=5)),
                ('card_cvv', models.CharField(max_length=3)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='byrno_pizza.pizza')),
            ],
        ),
    ]
