# Generated by Django 5.1.5 on 2025-02-12 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('byrno_pizza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
    ]
