# Generated by Django 5.1.5 on 2025-02-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byrno_pizza', '0002_remove_pizza_toppings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.CharField(choices=[('sizes', 'Pizza Sizes'), ('cheeses', 'Cheese Types'), ('sauces', 'Sauce Types')], max_length=10)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
