# Generated by Django 5.1.5 on 2025-02-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('byrno_pizza', '0003_pizzaoptions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PizzaOptions',
            new_name='PizzaOption',
        ),
    ]
